name: 24/7 IPTV Streamer

on:
  schedule:
    # Se reinicia automáticamente cada 5 horas para evitar cierres de GitHub
    - cron: '0 */5 * * *'
  workflow_dispatch: # Permite iniciar la transmisión manualmente

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Instalar FFmpeg y Fuentes
        run: sudo apt-get update && sudo apt-get install -y ffmpeg fonts-freefont-ttf

      - name: Iniciar Transmisión RTMP
        env:
          STREAM_URL: ${{ secrets.STREAM_URL }}
          STREAM_KEY: ${{ secrets.STREAM_KEY }}
        run: |
          chmod +x stream.sh
          ./stream.sh "$STREAM_URL" "$STREAM_KEY"
